# Generated by Django 5.2.1 on 2025-05-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_friend_id_friendrequest_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friend_id',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
