# Generated by Django 5.2.1 on 2025-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
