# Generated by Django 5.2.1 on 2025-06-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='group_posts/'),
        ),
    ]
